# Generated by Django 6.0.1 on 2026-02-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='activities',
            field=models.CharField(blank=True, help_text='Comma-separated: e.g. work,sleep,exercise', max_length=200),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='energy_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'Good'), (5, 'High')], null=True),
        ),
    ]
