# Generated by Django 6.0.1 on 2026-02-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0003_user_access_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccesslocation',
            name='location_source',
            field=models.CharField(choices=[('ip', 'IP geolocation'), ('browser', 'Browser GPS')], default='ip', max_length=10),
        ),
    ]
