# Generated by Django 6.0.1 on 2026-02-14 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0005_counsellor_chat_and_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='category',
            field=models.CharField(choices=[('support', 'Support'), ('discussion', 'Discussion'), ('recovery', 'Recovery Story')], default='support', max_length=20),
        ),
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quality', models.PositiveSmallIntegerField(choices=[(1, '1 – Very poor'), (2, '2 – Poor'), (3, '3 – Fair'), (4, '4 – Good'), (5, '5 – Very good')], help_text='1–5')),
                ('hours', models.DecimalField(decimal_places=1, help_text='Hours slept', max_digits=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
