# Generated by Django 6.0.2 on 2026-02-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0006_sleep_log_and_forum_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('booking_created', 'New booking'), ('chat_started', 'Chat started'), ('message_received', 'New message'), ('booking_status', 'Booking status changed')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Mind_Mend.counsellorbooking')),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mind_Mend.counsellor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
