# Generated by Django 6.0.2 on 2026-02-15 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0007_counsellornotification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SleepLog',
        ),
    ]
