# Generated by Django 6.0.1 on 2026-04-11 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0011_user_memory_preferred_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodentry',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='moodentry',
            unique_together=set(),
        ),
    ]
