# Generated by Django 6.0.1 on 2026-04-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0012_alter_moodentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='counsellors/'),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='session_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Session fee', max_digits=10),
        ),
    ]
