# Generated by Django 6.0.1 on 2026-04-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0013_counsellor_profile_picture_counsellor_session_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellorbooking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
