# Generated by Django 6.0.1 on 2026-04-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0013_counsellor_profile_picture_counsellor_session_fee'),
    ]

    operations = [
        # Use SeparateDatabaseAndState with IF NOT EXISTS to safely handle the
        # case where this column already exists in the production database.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE "Mind_Mend_counsellorbooking"
                        ADD COLUMN IF NOT EXISTS "is_paid" boolean NOT NULL DEFAULT false;
                    """,
                    reverse_sql="""
                        ALTER TABLE "Mind_Mend_counsellorbooking"
                        DROP COLUMN IF EXISTS "is_paid";
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='counsellorbooking',
                    name='is_paid',
                    field=models.BooleanField(default=False),
                ),
            ],
        ),
    ]
