# Generated by Django 6.0.1 on 2026-04-14 10:06

import Mind_Mend.encryption
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0015_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location_opt_out',
            field=models.BooleanField(default=False, help_text='If checked, location tracking is disabled for this user.'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=Mind_Mend.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='counsellorchatmessage',
            name='content',
            field=Mind_Mend.encryption.EncryptedTextField(),
        ),
    ]
