# Generated by Django 6.0.2 on 2026-06-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0018_emailverificationotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='consultation_fees_policy',
            field=models.TextField(blank=True, default='', help_text='Fees and follow-up policies'),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='medical_registration',
            field=models.CharField(blank=True, default='', help_text='Medical registration number', max_length=200),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='relevant_experience',
            field=models.TextField(blank=True, default='', help_text='Brief description of relevant experience'),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='review_quality',
            field=models.TextField(blank=True, default='', help_text='Summary of rating/review quality'),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='verified_qualification',
            field=models.TextField(blank=True, default='', help_text='Verified degrees and licenses'),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of professional experience'),
        ),
    ]
