# Generated by Django 6.0.2 on 2026-06-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0019_counsellor_consultation_fees_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='instant_session_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Instant session fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='is_instant_enabled',
            field=models.BooleanField(default=False, help_text='Available for instant counselling'),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='is_instant',
            field=models.BooleanField(default=False, help_text='Whether this is an instant booking'),
        ),
    ]
