# Generated by Django 6.0.1 on 2026-06-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0020_counsellor_instant_session_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellorbooking',
            name='chat_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='include_chat',
            field=models.BooleanField(default=True, help_text='Include Chat Session'),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='include_video',
            field=models.BooleanField(default=False, help_text='Include Video Calling Session'),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='video_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
