# Generated by Django 6.0.1 on 2026-06-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0021_counsellorbooking_chat_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='instant_video_session_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Instant video session fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='video_session_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Video session fee', max_digits=10),
        ),
    ]
