# Generated by Django 6.0.1 on 2026-06-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0022_counsellor_instant_video_session_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_complete',
            field=models.BooleanField(default=False, help_text='Set to True after the user completes the mandatory profile setup after registration.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_username',
            field=models.BooleanField(default=True, help_text='If True, your @username is shown to counsellors and in the community forum. If False, you appear as Anonymous everywhere.'),
        ),
    ]
