# Generated by Django 6.0.1 on 2026-06-17 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0023_add_profile_complete_show_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='MindMend credits awarded as compensation.', max_digits=10),
        ),
        migrations.CreateModel(
            name='BookingCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Internal reason for cancellation')),
                ('message_to_patient', models.TextField(help_text='Message to display to the patient')),
                ('compensation_credited', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refund_status', models.CharField(default='Initiated', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='Mind_Mend.counsellorbooking')),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mind_Mend.counsellor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
