# Generated by Django 6.0.1 on 2026-06-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0025_counsellorbooking_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellorbooking',
            name='counsellor_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total fee minus platform commission', max_digits=10),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='is_settled',
            field=models.BooleanField(default=False, help_text='Has MindMend paid the counsellor for this session?'),
        ),
    ]
