# Generated by Django 6.0.1 on 2026-06-18 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0026_counsellorbooking_counsellor_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcancellation',
            name='counsellor_penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Fine deducted from counsellor's payout", max_digits=10),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the session was marked as completed', null=True),
        ),
        migrations.AlterField(
            model_name='bookingcancellation',
            name='message_to_patient',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookingcancellation',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookingcancellation',
            name='refund_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='CounsellorBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('counsellor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='Mind_Mend.counsellor')),
            ],
        ),
    ]
