# Generated by Django 6.0.1 on 2026-06-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0027_bookingcancellation_counsellor_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellorbooking',
            name='completion_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
