# Generated by Django 6.0.1 on 2026-06-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0028_counsellorbooking_completion_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approved by admin to practice'),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='trust_score',
            field=models.IntegerField(default=100, help_text='Decreases on no-shows or bad behavior'),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('counsellor', 'Counsellor'), ('patient', 'Patient'), ('system', 'System')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='is_no_show',
            field=models.BooleanField(default=False, help_text='True if either party was marked as no-show'),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Can receive new bookings'),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='session_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee per 30-minute session', max_digits=10),
        ),
        migrations.AlterField(
            model_name='counsellorbooking',
            name='is_instant',
            field=models.BooleanField(default=False),
        ),
    ]
