# Generated by Django 6.0.1 on 2026-06-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0029_counsellor_is_approved_counsellor_trust_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellorbooking',
            name='actual_duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='counsellor_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='patient_joined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='session_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
