# Generated by Django 6.0.1 on 2026-06-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0030_counsellorbooking_actual_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='outstanding_debt',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Unpaid penalties carried forward', max_digits=10),
        ),
    ]
