# Generated by Django 6.0.1 on 2026-06-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0031_counsellor_outstanding_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellorbooking',
            name='bonus_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Bonus credits used', max_digits=10),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='wallet_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cash balance used', max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bonus_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Promotional or compensation credits awarded to the user.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='counsellorbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Real cash deposited by the user.', max_digits=10),
        ),
    ]
