# Generated by Django 6.0.1 on 2026-06-18 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0032_counsellorbooking_bonus_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellorbooking',
            name='is_disputed',
            field=models.BooleanField(default=False, help_text='True if patient raised a dispute'),
        ),
        migrations.CreateModel(
            name='SessionDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_reason', models.TextField()),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin resolution')),
                ('outcome', models.CharField(choices=[('pending', 'Pending Admin Review'), ('patient_won', 'Resolved in favor of Patient'), ('counsellor_won', 'Resolved in favor of Counsellor')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='Mind_Mend.counsellorbooking')),
            ],
        ),
    ]
