# Generated by Django 6.0.1 on 2026-06-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0034_bonuscredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellorbooking',
            name='counsellor_requested_finish',
            field=models.BooleanField(default=False, help_text='Counsellor wants to end session early'),
        ),
        migrations.AddField(
            model_name='counsellorbooking',
            name='patient_requested_finish',
            field=models.BooleanField(default=False, help_text='Patient wants to end session early'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('add_money', 'Added Money'), ('session_booking', 'Session Booking'), ('compensation', 'Compensation Credit'), ('refund', 'Refund Credit'), ('expired', 'Expired Bonus')], max_length=50),
        ),
    ]
