# Generated by Django 6.0.1 on 2026-06-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mind_Mend', '0036_payoutsettlement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellorbooking',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Flat convenience fee charged to the patient (₹2 normal, ₹3 instant)', max_digits=10),
        ),
    ]
